Various - See ChangeLog

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23600,7 +23600,75 @@ fi
 #define USE_DB41 1
 _ACEOF
 
-	fi
+		MYOLDLIBS="$LIBS"
+		for MYOCLIBS in db db-4.5 db-4.4 db-4.3 db-4.2 db-4.1
+		do
+			LIBS="$MYOLDLIBS -l$MYOCLIBS"
+			if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <db.h>
+int
+main ()
+{
+
+			int major, minor, patch;
+			db_version (&major, &minor, &patch);
+			if (major == 4 && minor > 0) {
+				return 0;
+			}
+			if (major > 4) {
+				return 0;
+			}
+			return 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  USE_DB="yes"
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+			if test "$USE_DB" != "no"
+			then
+				LIBCOB_LIBS="$LIBCOB_LIBS -l$MYOCLIBS"
+				break
+			fi
+		done
+		LIBS="$MYOLDLIBS"
+		if test "$USE_DB" != "yes"
+		then
+			{ { echo "$as_me:$LINENO: error: Include file db.h implies version >=4.1 but no library found" >&5
+echo "$as_me: error: Include file db.h implies version >=4.1 but no library found" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+	else
 
 
 
@@ -23759,7 +23827,7 @@ fi
 
 done
 
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.5" >&5
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4.5" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.5... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_5___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -23896,9 +23964,9 @@ fi
 
 fi
 
-	if test "$USE_DB" != "yes"
-	then
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.4" >&5
+		if test "$USE_DB" != "yes"
+		then
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4.4" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.4... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_4___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24035,10 +24103,10 @@ fi
 
 fi
 
-	fi
-	if test "$USE_DB" != "yes"
-	then
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.3" >&5
+		fi
+		if test "$USE_DB" != "yes"
+		then
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4.3" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.3... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_3___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24175,10 +24243,10 @@ fi
 
 fi
 
-	fi
-	if test "$USE_DB" != "yes"
-	then
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.2" >&5
+		fi
+		if test "$USE_DB" != "yes"
+		then
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4.2" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.2... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_2___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24315,10 +24383,10 @@ fi
 
 fi
 
-	fi
-	if test "$USE_DB" != "yes"
-	then
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.1" >&5
+		fi
+		if test "$USE_DB" != "yes"
+		then
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4.1" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.1... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_1___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24455,16 +24523,14 @@ fi
 
 fi
 
-	fi
-	if test "$USE_DB" != "yes"
-	then
-		if test "$HAS_DB41" != "no"
-		then
-			{ { echo "$as_me:$LINENO: error: Include file db.h implies version >=4.1 but no library found" >&5
-echo "$as_me: error: Include file db.h implies version >=4.1 but no library found" >&2;}
-   { (exit 1); exit 1; }; }
 		fi
-	echo "$as_me:$LINENO: checking for __db_open in -ldb-4" >&5
+		if test "$USE_DB" != "yes"
+		then
+#			if test "$HAS_DB41" != "no"
+#			then
+#				AC_MSG_ERROR(Include file db.h implies version >=4.1 but no library found)
+#			fi
+		echo "$as_me:$LINENO: checking for __db_open in -ldb-4" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24601,11 +24667,11 @@ fi
 
 fi
 
-	fi
+		fi
 
-	if test "$USE_DB" != "yes"
-	then
-	echo "$as_me:$LINENO: checking for __db_open in -ldb" >&5
+		if test "$USE_DB" != "yes"
+		then
+		echo "$as_me:$LINENO: checking for __db_open in -ldb" >&5
 echo $ECHO_N "checking for __db_open in -ldb... $ECHO_C" >&6
 if test "${ac_cv_lib_db___db_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24746,6 +24812,7 @@ fi
 
 fi
 
+		fi
 	fi
 fi
 
