See ChangeLogs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4167,7 +4167,9 @@ then
 
 
 
-for ac_header in db.h db_185.h db3/db_185.h db4/db_185.h db4.1/db_185.h db4.2/db_185.h db4.3/db_185.h
+
+
+for ac_header in db.h db_185.h db3/db_185.h db4/db_185.h db4.1/db_185.h db4.2/db_185.h db4.3/db_185.h db4.4/db_185.h db4.5/db_185.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -4316,6 +4318,285 @@ fi
 
 done
 
+	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.5" >&5
+echo $ECHO_N "checking for __db_open in -ldb-4.5... $ECHO_C" >&6
+if test "${ac_cv_lib_db_4_5___db_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldb-4.5  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __db_open ();
+int
+main ()
+{
+__db_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_db_4_5___db_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_db_4_5___db_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_5___db_open" >&5
+echo "${ECHO_T}$ac_cv_lib_db_4_5___db_open" >&6
+if test $ac_cv_lib_db_4_5___db_open = yes; then
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.5"
+else
+  echo "$as_me:$LINENO: checking for dbopen in -ldb-4.5" >&5
+echo $ECHO_N "checking for dbopen in -ldb-4.5... $ECHO_C" >&6
+if test "${ac_cv_lib_db_4_5_dbopen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldb-4.5  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dbopen ();
+int
+main ()
+{
+dbopen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_db_4_5_dbopen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_db_4_5_dbopen=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_5_dbopen" >&5
+echo "${ECHO_T}$ac_cv_lib_db_4_5_dbopen" >&6
+if test $ac_cv_lib_db_4_5_dbopen = yes; then
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.5"
+fi
+
+fi
+
+	if test "$USE_DB" != "yes"
+	then
+	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.4" >&5
+echo $ECHO_N "checking for __db_open in -ldb-4.4... $ECHO_C" >&6
+if test "${ac_cv_lib_db_4_4___db_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldb-4.4  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char __db_open ();
+int
+main ()
+{
+__db_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_db_4_4___db_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_db_4_4___db_open=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_4___db_open" >&5
+echo "${ECHO_T}$ac_cv_lib_db_4_4___db_open" >&6
+if test $ac_cv_lib_db_4_4___db_open = yes; then
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.4"
+else
+  echo "$as_me:$LINENO: checking for dbopen in -ldb-4.4" >&5
+echo $ECHO_N "checking for dbopen in -ldb-4.4... $ECHO_C" >&6
+if test "${ac_cv_lib_db_4_4_dbopen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldb-4.4  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dbopen ();
+int
+main ()
+{
+dbopen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_db_4_4_dbopen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_db_4_4_dbopen=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_4_dbopen" >&5
+echo "${ECHO_T}$ac_cv_lib_db_4_4_dbopen" >&6
+if test $ac_cv_lib_db_4_4_dbopen = yes; then
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.4"
+fi
+
+fi
+
+	fi
+	if test "$USE_DB" != "yes"
+	then
 	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.3" >&5
 echo $ECHO_N "checking for __db_open in -ldb-4.3... $ECHO_C" >&6
 if test "${ac_cv_lib_db_4_3___db_open+set}" = set; then
@@ -4448,11 +4729,12 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_3_dbopen" >&5
 echo "${ECHO_T}$ac_cv_lib_db_4_3_dbopen" >&6
 if test $ac_cv_lib_db_4_3_dbopen = yes; then
-  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb"-4.3
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.3"
 fi
 
 fi
 
+	fi
 	if test "$USE_DB" != "yes"
 	then
 	echo "$as_me:$LINENO: checking for __db_open in -ldb-4.2" >&5
@@ -4587,7 +4869,7 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_2_dbopen" >&5
 echo "${ECHO_T}$ac_cv_lib_db_4_2_dbopen" >&6
 if test $ac_cv_lib_db_4_2_dbopen = yes; then
-  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb"-4.2
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.2"
 fi
 
 fi
@@ -4727,7 +5009,7 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_1_dbopen" >&5
 echo "${ECHO_T}$ac_cv_lib_db_4_1_dbopen" >&6
 if test $ac_cv_lib_db_4_1_dbopen = yes; then
-  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb"-4.1
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4.1"
 fi
 
 fi
@@ -4867,7 +5149,7 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_db_4_dbopen" >&5
 echo "${ECHO_T}$ac_cv_lib_db_4_dbopen" >&6
 if test $ac_cv_lib_db_4_dbopen = yes; then
-  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb"-4
+  USE_DB="yes" LIBCOB_LIBS="$LIBCOB_LIBS -ldb-4"
 fi
 
 fi
@@ -7977,7 +8259,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7980 "configure"' > conftest.$ac_ext
+  echo '#line 8262 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9313,7 +9595,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:9316:" \
+echo "$as_me:9598:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -10347,11 +10629,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10350: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10354: \$? = $ac_status" >&5
+   echo "$as_me:10636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10580,11 +10862,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10583: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10865: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10587: \$? = $ac_status" >&5
+   echo "$as_me:10869: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10640,11 +10922,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10643: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10925: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10647: \$? = $ac_status" >&5
+   echo "$as_me:10929: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12824,7 +13106,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12827 "configure"
+#line 13109 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12922,7 +13204,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12925 "configure"
+#line 13207 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15101,11 +15383,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15104: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15386: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15108: \$? = $ac_status" >&5
+   echo "$as_me:15390: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15161,11 +15443,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15164: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15446: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15168: \$? = $ac_status" >&5
+   echo "$as_me:15450: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16522,7 +16804,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16525 "configure"
+#line 16807 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16620,7 +16902,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16623 "configure"
+#line 16905 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17447,11 +17729,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17450: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17732: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17454: \$? = $ac_status" >&5
+   echo "$as_me:17736: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17507,11 +17789,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17510: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17514: \$? = $ac_status" >&5
+   echo "$as_me:17796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19541,11 +19823,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19826: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19548: \$? = $ac_status" >&5
+   echo "$as_me:19830: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19774,11 +20056,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19777: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20059: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19781: \$? = $ac_status" >&5
+   echo "$as_me:20063: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19834,11 +20116,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19837: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20119: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19841: \$? = $ac_status" >&5
+   echo "$as_me:20123: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22018,7 +22300,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 22021 "configure"
+#line 22303 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22116,7 +22398,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 22119 "configure"
+#line 22401 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23333,7 +23615,8 @@ fi
 
 
 
-for ac_header in signal.h fcntl.h malloc.h locale.h stddef.h wchar.h
+
+for ac_header in sys/types.h signal.h fcntl.h malloc.h locale.h stddef.h wchar.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
