Variable file realization

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1051,6 +1051,7 @@ Optional Packages:
   --with-lfs64            use large file system for file I/O (default)
   --with-dl               use system dynamic loader
   --with-patch-level      define a patch level (default 0)
+  --with-varseq           define variable sequential format (default 0)
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-libiconv-prefix[=DIR]  search for libiconv in DIR/include and DIR/lib
   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
@@ -1997,6 +1998,8 @@ fi
 
 
 # Autoheader templates
+
+
 
 
 
@@ -3503,6 +3506,33 @@ esac
 fi;
 cat >>confdefs.h <<_ACEOF
 #define PATCH_LEVEL $PATCH_LEVEL
+_ACEOF
+
+
+WITH_VARSEQ=0
+
+# Check whether --with-varseq or --without-varseq was given.
+if test "${with_varseq+set}" = set; then
+  withval="$with_varseq"
+  case $with_varseq in
+    yes)	{ { echo "$as_me:$LINENO: error: \"You must give --with-varseq an argument.\"" >&5
+echo "$as_me: error: \"You must give --with-varseq an argument.\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+    no)		{ { echo "$as_me:$LINENO: error: \"--without-varseq not supported.\"" >&5
+echo "$as_me: error: \"--without-varseq not supported.\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+    [0-2])	WITH_VARSEQ=$with_varseq
+		;;
+    *)		{ { echo "$as_me:$LINENO: error: \"Invalid --with-varseq argument\"" >&5
+echo "$as_me: error: \"Invalid --with-varseq argument\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+esac
+fi;
+cat >>confdefs.h <<\_ACEOF
+#define WITH_VARSEQ 1
 _ACEOF
 
 
@@ -8419,7 +8449,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8422 "configure"' > conftest.$ac_ext
+  echo '#line 8452 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9755,7 +9785,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:9758:" \
+echo "$as_me:9788:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -10789,11 +10819,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10792: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10822: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10796: \$? = $ac_status" >&5
+   echo "$as_me:10826: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11022,11 +11052,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11025: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11055: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11029: \$? = $ac_status" >&5
+   echo "$as_me:11059: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11082,11 +11112,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11085: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11115: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11089: \$? = $ac_status" >&5
+   echo "$as_me:11119: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13266,7 +13296,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13269 "configure"
+#line 13299 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13364,7 +13394,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13367 "configure"
+#line 13397 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15543,11 +15573,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15546: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15576: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15550: \$? = $ac_status" >&5
+   echo "$as_me:15580: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15603,11 +15633,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15606: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15636: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15610: \$? = $ac_status" >&5
+   echo "$as_me:15640: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16964,7 +16994,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16967 "configure"
+#line 16997 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17062,7 +17092,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17065 "configure"
+#line 17095 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17889,11 +17919,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17892: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17922: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17896: \$? = $ac_status" >&5
+   echo "$as_me:17926: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17949,11 +17979,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17952: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17982: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17956: \$? = $ac_status" >&5
+   echo "$as_me:17986: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19983,11 +20013,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19986: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19990: \$? = $ac_status" >&5
+   echo "$as_me:20020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -20216,11 +20246,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20219: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20249: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20223: \$? = $ac_status" >&5
+   echo "$as_me:20253: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -20276,11 +20306,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20279: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20309: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20283: \$? = $ac_status" >&5
+   echo "$as_me:20313: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22460,7 +22490,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 22463 "configure"
+#line 22493 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22558,7 +22588,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 22561 "configure"
+#line 22591 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
