Change to ANSI 85 testsuite (make test):
cobol85/Makefile.am: added target for decompressing newcob.val.Z and download it

git-svn-id: https://svn.code.sf.net/p/open-cobol/code/branches/gnu-cobol-2.0@716 ed166372-6744-4ac0-a67f-bb1ae9efa102

diff --git a/tests/cobol85/Makefile.in b/tests/cobol85/Makefile.in
--- a/tests/cobol85/Makefile.in
+++ b/tests/cobol85/Makefile.in
@@ -17,8 +17,8 @@
 #
 # Makefile gnucobol/tests/cobol85
 #
-# Copyright (C) 2003-2012 Free Software Foundation, Inc.
-# Written by Keisuke Nishida, Roger While
+# Copyright (C) 2003-2012, 2015 Free Software Foundation, Inc.
+# Written by Keisuke Nishida, Roger While, Simon Sobisch
 #
 # This file is part of GnuCOBOL.
 #
@@ -525,6 +525,23 @@ diff:
 
 clean-local:
 	rm -rf copy copyalt $(MODULES) EXEC85 summary.log EXEC85.cob
+
+newcob.val:
+	if ! test -f "newcob.val"; then \
+#	   echo "newcob.val missing"; \
+	   if ! test -f "newcob.val.Z"; then \
+#	      echo "newcob.val.Z missing"; \
+	      wget "http://www.itl.nist.gov/div897/ctg/suites/newcob.val.Z"; \
+	   fi; \
+	   if test -f "newcob.val.Z"; then \
+#	      echo "unpacking newcob.val"; \
+	      gunzip newcob.val.Z || gzip -d newcob.val.Z || uncompress newcob.val.Z; \
+	   fi; \
+	   if ! test -f "newcob.val"; then \
+	      echo "newcob.val missing, automatic download and uncompress did not work"; \
+	      exit 1; \
+	   fi; \
+	fi
 
 $(MODULES): newcob.val EXEC85 $(srcdir)/EXEC85.conf.in
 	@echo -n "Building module directory $@ ..."
