Fixes for 32/64 bit pointer listing test. Picture and TYPE field additions and changes.
git-svn-id: https://svn.code.sf.net/p/open-cobol/code/branches/gnu-cobol-2.0@1007 ed166372-6744-4ac0-a67f-bb1ae9efa102

diff --git a/tests/testsuite b/tests/testsuite
--- a/tests/testsuite
+++ b/tests/testsuite
@@ -831,9 +831,9 @@ at_help_all="1;used_binaries.at:21;Compiler outputs;runmisc cobc;
 219;listings.at:715;Two source files;listing;
 220;listings.at:793;Error/Warning messages;listing;
 221;listings.at:951;Symbols;listing;
-222;listings.at:1338;Conditional compilation;listing;
-223;listings.at:1404;LISTING ON/OFF;listing;
-224;listings.at:1491;File descriptions;listing;
+222;listings.at:1460;Conditional compilation;listing;
+223;listings.at:1526;LISTING ON/OFF;listing;
+224;listings.at:1613;File descriptions;listing;
 225;run_fundamental.at:23;DISPLAY literals;fundamental;
 226;run_fundamental.at:79;DISPLAY literals, DECIMAL-POINT is COMMA;fundamental;
 227;run_fundamental.at:118;Hexadecimal literal;fundamental;
@@ -17929,11 +17929,11 @@ SIZE TYPE           LVL  NAME                           PICTURE
 
 0004 ALPHANUMERIC   01   WS-THREE                       X(4)
 
-0004 NUMERIC        01   WS-FOUR                        S9(7)V9(8)
+0004 NUMERIC        01   WS-FOUR                        S9(7)V9(8) COMP-1
 
-0008 NUMERIC        01   WS-FIVE                        S9(17)V9(17)
+0008 NUMERIC        01   WS-FIVE                        S9(17)V9(17) COMP-2
 
-0002 NUMERIC        01   WS-SIX                         S999
+0002 NUMERIC        01   WS-SIX                         S999 COMP-3
 
 0013 NUMERIC        01   WS-SEVEN                       $$,$$$,$$9.99
 
@@ -18037,6 +18037,36 @@ $at_failed && at_fn_log_failure  \
 $at_traceon; }
 
 
+# Check for 32/64bit first
+cat >P64.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      P64.
+       DATA             DIVISION.
+       PROCEDURE        DIVISION.
+       >>IF P64 SET
+           DISPLAY 'X'
+           END-DISPLAY.
+       >>END-IF
+           STOP RUN.
+_ATEOF
+
+
+{ set +x
+$as_echo "$at_srcdir/listings.at:1084: \$COMPILE -o P64 P64.cob"
+at_fn_check_prepare_dynamic "$COMPILE -o P64 P64.cob" "listings.at:1084"
+( $at_check_trace; $COMPILE -o P64 P64.cob
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1084"
+$at_failed && at_fn_log_failure  \
+"prog.lis"
+$at_traceon; }
+
+
 cat >prog3.cob <<'_ATEOF'
 
        IDENTIFICATION   DIVISION.
@@ -18088,21 +18118,21 @@ _ATEOF
 
 daymon=`date +"%a %b %e"`
 { set +x
-$as_echo "$at_srcdir/listings.at:1119: \$COMPILE_ONLY -t prog.lst prog3.cob"
-at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog3.cob" "listings.at:1119"
+$as_echo "$at_srcdir/listings.at:1134: \$COMPILE_ONLY -t prog.lst prog3.cob"
+at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog3.cob" "listings.at:1134"
 ( $at_check_trace; $COMPILE_ONLY -t prog.lst prog3.cob
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1119"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1134"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
 
 
-cat >prog17.lst <<'_ATEOF'
+cat >prog17-64.lst <<'_ATEOF'
 GnuCOBOL 2.0.0   prog3.cob                  DDD MMM dd HH:MM:SS YYYY  Page 0001
 
 LINE    PG/LN  A...B............................................................
@@ -18159,11 +18189,11 @@ SIZE TYPE           LVL  NAME                           PICTURE
 0512 ALPHANUMERIC   77   WS-Where                       X(512)
 
 4540 GROUP          01   ws-mysql
-0008 ALPHANUMERIC   02     ws-mysql-cid                 9(10)
-0008 ALPHANUMERIC   02     ws-mysql-result              9(10)
-0008 ALPHANUMERIC   02     ws-mysql-result-2            9(10)
-0008 ALPHANUMERIC   02     ws-mysql-result-3            9(10)
-0004 ALPHANUMERIC   02     ws-mysql-count-rows          S9(9)
+0008 POINTER        02     ws-mysql-cid
+0008 POINTER        02     ws-mysql-result
+0008 POINTER        02     ws-mysql-result-2
+0008 POINTER        02     ws-mysql-result-3
+0004 NUMERIC        02     ws-mysql-count-rows          S9(9) COMP
 0004 ALPHANUMERIC   02     ws-mysql-error-number        X(4)
 0080 ALPHANUMERIC   02     ws-mysql-error-message       X(80)
 0064 ALPHANUMERIC   02     ws-mysql-host-name           X(64)
@@ -18177,9 +18207,107 @@ SIZE TYPE           LVL  NAME                           PICTURE
 0004 ALPHANUMERIC   01   ws-No-Paragraph                9(4)
 
 0006 GROUP          01   subscripts
-0002 ALPHANUMERIC   12     J                            S9(4)
-0002 ALPHANUMERIC   12     K                            S9(4)
-0002 ALPHANUMERIC   12     L                            S9(4)
+0002 NUMERIC        12     J                            S9(4) COMP-5
+0002 NUMERIC        12     K                            S9(4) COMP-5
+0002 NUMERIC        12     L                            S9(4) COMP-5
+
+0078 GROUP          01   Display-Message-1
+0009 ALPHANUMERIC   03     FILLER                       X(9)
+0069 ALPHANUMERIC   03     FILLER                       X(69)
+
+0318 GROUP          01   Display-Message-2
+0018 ALPHANUMERIC   03     FILLER                       X(18)
+0004 ALPHANUMERIC   03     FILLER                       X(4)
+0006 ALPHANUMERIC   03     FILLER                       X(6)
+0003 ALPHANUMERIC   03     FILLER                       9(3)
+0009 ALPHANUMERIC   03     FILLER                       X(9)
+0199 ALPHANUMERIC   03     FILLER                       X(199)
+0012 ALPHANUMERIC   03     FILLER                       X(12)
+0067 ALPHANUMERIC   03     FILLER                       X(67)
+
+0 Warnings in program
+0 Errors in program
+_ATEOF
+
+
+cat >prog17-32.lst <<'_ATEOF'
+GnuCOBOL 2.0.0   prog3.cob                  DDD MMM dd HH:MM:SS YYYY  Page 0001
+
+LINE    PG/LN  A...B............................................................
+
+000001
+000002         IDENTIFICATION   DIVISION.
+000003         PROGRAM-ID.      prog.
+000004         DATA             DIVISION.
+000005         WORKING-STORAGE  SECTION.
+000006         77  WS-Where           pic x(512).
+000007
+000008         01  ws-mysql.
+000009             02  ws-mysql-cid                        usage pointer.
+000010             02  ws-mysql-result                     usage pointer.
+000011             02  ws-mysql-result-2                   usage pointer.
+000012             02  ws-mysql-result-3                   usage pointer.
+000013             02  ws-mysql-count-rows                 pic s9(9) comp.
+000014             02  ws-mysql-error-number               pic x(4).
+000015             02  ws-mysql-error-message              pic x(80).
+000016             02  ws-mysql-host-name                  pic x(64).
+000017             02  ws-mysql-implementation             pic x(64).
+000018             02  ws-mysql-password                   pic x(64).
+000019             02  ws-mysql-base-name                  pic x(64).
+000020             02  ws-mysql-port-number                pic x(4).
+000021             02  ws-mysql-socket                     pic x(64).
+000022             02  ws-mysql-command                    pic x(4096).
+000023
+000024         01  ws-No-Paragraph pic 9(4).
+000025
+000026         01  subscripts usage comp-5.
+000027             12 J                    pic s9(4).
+000028             12 K                    pic s9(4).
+000029             12 L                    pic s9(4).
+000030
+000031         SCREEN           SECTION.
+000032         01  Display-Message-1 foreground-color 2.
+000033             03  value "WS-Where=" line 23 col  1.
+000034             03  from WS-Where (1:J) pic x(69) col 10.
+000035         01  Display-Message-2 foreground-color 2.
+000036             03  value "ST004 SQL Err No.=" line 4 col  1.
+000037             03  using ws-mysql-error-number pic x(4) col 19.
+000038             03  value " Para=" col 23.
+000039             03  using WS-No-Paragraph pic 9(3) col 29.
+000040             03  value " SQL Cmd=" col 32.
+000041             03  using ws-mysql-command pic x(199) col 41.
+000042             03  value "SQL Err Msg=" line 7 col  1.
+000043             03  using ws-mysql-error-message pic x(67) col 13.
+000044         PROCEDURE        DIVISION.
+000045             STOP RUN.
+GnuCOBOL 2.0.0   prog3.cob                  DDD MMM dd HH:MM:SS YYYY  Page 0002
+
+SIZE TYPE           LVL  NAME                           PICTURE
+
+0512 ALPHANUMERIC   77   WS-Where                       X(512)
+
+4524 GROUP          01   ws-mysql
+0004 POINTER        02     ws-mysql-cid
+0004 POINTER        02     ws-mysql-result
+0004 POINTER        02     ws-mysql-result-2
+0004 POINTER        02     ws-mysql-result-3
+0004 NUMERIC        02     ws-mysql-count-rows          S9(9) COMP
+0004 ALPHANUMERIC   02     ws-mysql-error-number        X(4)
+0080 ALPHANUMERIC   02     ws-mysql-error-message       X(80)
+0064 ALPHANUMERIC   02     ws-mysql-host-name           X(64)
+0064 ALPHANUMERIC   02     ws-mysql-implementation      X(64)
+0064 ALPHANUMERIC   02     ws-mysql-password            X(64)
+0064 ALPHANUMERIC   02     ws-mysql-base-name           X(64)
+0004 ALPHANUMERIC   02     ws-mysql-port-number         X(4)
+0064 ALPHANUMERIC   02     ws-mysql-socket              X(64)
+4096 ALPHANUMERIC   02     ws-mysql-command             X(4096)
+
+0004 ALPHANUMERIC   01   ws-No-Paragraph                9(4)
+
+0006 GROUP          01   subscripts
+0002 NUMERIC        12     J                            S9(4) COMP-5
+0002 NUMERIC        12     K                            S9(4) COMP-5
+0002 NUMERIC        12     L                            S9(4) COMP-5
 
 0078 GROUP          01   Display-Message-1
 0009 ALPHANUMERIC   03     FILLER                       X(9)
@@ -18202,16 +18330,54 @@ _ATEOF
 
 sed -e 's/'"$daymon"'/DDD MMM dd/g' -f sed.txt <prog.lst >prog.lis
 
+
 { set +x
-$as_echo "$at_srcdir/listings.at:1220: diff prog17.lst prog.lis"
-at_fn_check_prepare_trace "listings.at:1220"
-( $at_check_trace; diff prog17.lst prog.lis
+$as_echo "$at_srcdir/listings.at:1333: ./P64"
+at_fn_check_prepare_trace "listings.at:1333"
+( $at_check_trace; ./P64
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+echo >>"$at_stdout"; $as_echo "X
+" | \
+  $at_diff - "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1333"
+if $at_failed; then :
+  # Previous test "failed" --> P64 showed no 'X' --> 32 bit
+{ set +x
+$as_echo "$at_srcdir/listings.at:1333: diff prog17-32.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1333"
+( $at_check_trace; diff prog17-32.lst prog.lis
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1220"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1333"
+$at_failed && at_fn_log_failure  \
+"prog.lis"
+$at_traceon; }
+
+
+else
+  # Previous test "passed" --> P64 showed 'X' --> 64 bit
+{ set +x
+$as_echo "$at_srcdir/listings.at:1333: diff prog17-64.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1333"
+( $at_check_trace; diff prog17-64.lst prog.lis
+) >>"$at_stdout" 2>>"$at_stderr" 5>&-
+at_status=$? at_failed=false
+$at_check_filter
+at_fn_diff_devnull "$at_stderr" || at_failed=:
+at_fn_diff_devnull "$at_stdout" || at_failed=:
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1333"
+$at_failed && at_fn_log_failure  \
+"prog.lis"
+$at_traceon; }
+
+
+fi
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
@@ -18263,15 +18429,15 @@ _ATEOF
 
 daymon=`date +"%a %b %e"`
 { set +x
-$as_echo "$at_srcdir/listings.at:1265: \$COMPILE_ONLY -t prog.lst prog4.cob"
-at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog4.cob" "listings.at:1265"
+$as_echo "$at_srcdir/listings.at:1387: \$COMPILE_ONLY -t prog.lst prog4.cob"
+at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog4.cob" "listings.at:1387"
 ( $at_check_trace; $COMPILE_ONLY -t prog.lst prog4.cob
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1265"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1387"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
@@ -18346,15 +18512,15 @@ _ATEOF
 sed -e 's/'"$daymon"'/DDD MMM dd/g' -f sed.txt <prog.lst >prog.lis
 
 { set +x
-$as_echo "$at_srcdir/listings.at:1334: diff prog18.lst prog.lis"
-at_fn_check_prepare_trace "listings.at:1334"
+$as_echo "$at_srcdir/listings.at:1456: diff prog18.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1456"
 ( $at_check_trace; diff prog18.lst prog.lis
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1334"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1456"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
@@ -18366,7 +18532,7 @@ $at_traceon; }
 read at_status <"$at_status_file"
 #AT_STOP_221
 #AT_START_222
-at_fn_group_banner 222 'listings.at:1338' \
+at_fn_group_banner 222 'listings.at:1460' \
   "Conditional compilation" "                        " 3
 at_xfail=no
 (
@@ -18403,15 +18569,15 @@ _ATEOF
 
 daymon=`date +"%a %b %e"`
 { set +x
-$as_echo "$at_srcdir/listings.at:1365: \$COMPILE_ONLY -DACTIVATE2 -t prog.lst prog.cob"
-at_fn_check_prepare_dynamic "$COMPILE_ONLY -DACTIVATE2 -t prog.lst prog.cob" "listings.at:1365"
+$as_echo "$at_srcdir/listings.at:1487: \$COMPILE_ONLY -DACTIVATE2 -t prog.lst prog.cob"
+at_fn_check_prepare_dynamic "$COMPILE_ONLY -DACTIVATE2 -t prog.lst prog.cob" "listings.at:1487"
 ( $at_check_trace; $COMPILE_ONLY -DACTIVATE2 -t prog.lst prog.cob
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1365"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1487"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
@@ -18451,15 +18617,15 @@ _ATEOF
 sed -e 's/'"$daymon"'/DDD MMM dd/g' -f sed.txt <prog.lst >prog.lis
 
 { set +x
-$as_echo "$at_srcdir/listings.at:1400: diff prog16.lst prog.lis"
-at_fn_check_prepare_trace "listings.at:1400"
+$as_echo "$at_srcdir/listings.at:1522: diff prog16.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1522"
 ( $at_check_trace; diff prog16.lst prog.lis
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1400"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1522"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
@@ -18471,7 +18637,7 @@ $at_traceon; }
 read at_status <"$at_status_file"
 #AT_STOP_222
 #AT_START_223
-at_fn_group_banner 223 'listings.at:1404' \
+at_fn_group_banner 223 'listings.at:1526' \
   "LISTING ON/OFF" "                                 " 3
 at_xfail=no
 (
@@ -18516,15 +18682,15 @@ _ATEOF
 
 daymon=`date +"%a %b %e"`
 { set +x
-$as_echo "$at_srcdir/listings.at:1437: \$COMPILE_ONLY -t prog.lst prog.cob"
-at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog.cob" "listings.at:1437"
+$as_echo "$at_srcdir/listings.at:1559: \$COMPILE_ONLY -t prog.lst prog.cob"
+at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog.cob" "listings.at:1559"
 ( $at_check_trace; $COMPILE_ONLY -t prog.lst prog.cob
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1437"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1559"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
@@ -18579,15 +18745,15 @@ _ATEOF
 sed -e 's/'"$daymon"'/DDD MMM dd/g' -f sed.txt <prog.lst >prog.lis
 
 { set +x
-$as_echo "$at_srcdir/listings.at:1487: diff prog17.lst prog.lis"
-at_fn_check_prepare_trace "listings.at:1487"
+$as_echo "$at_srcdir/listings.at:1609: diff prog17.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1609"
 ( $at_check_trace; diff prog17.lst prog.lis
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1487"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1609"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
@@ -18599,7 +18765,7 @@ $at_traceon; }
 read at_status <"$at_status_file"
 #AT_STOP_223
 #AT_START_224
-at_fn_group_banner 224 'listings.at:1491' \
+at_fn_group_banner 224 'listings.at:1613' \
   "File descriptions" "                              " 3
 at_xfail=no
 (
@@ -18730,8 +18896,8 @@ _ATEOF
 
 daymon=`date +"%a %b %e"`
 { set +x
-$as_echo "$at_srcdir/listings.at:1612: \$COMPILE_ONLY -t prog.lst prog.cob"
-at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog.cob" "listings.at:1612"
+$as_echo "$at_srcdir/listings.at:1734: \$COMPILE_ONLY -t prog.lst prog.cob"
+at_fn_check_prepare_dynamic "$COMPILE_ONLY -t prog.lst prog.cob" "listings.at:1734"
 ( $at_check_trace; $COMPILE_ONLY -t prog.lst prog.cob
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
@@ -18747,7 +18913,7 @@ prog.cob: 66: Warning: DATA RECORDS is obsolete in GnuCOBOL
 " | \
   $at_diff - "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1612"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1734"
 $at_failed && at_fn_log_failure
 $at_traceon; }
 
@@ -18964,15 +19130,15 @@ _ATEOF
 sed -e 's/'"$daymon"'/DDD MMM dd/g' -f sed.txt <prog.lst >prog.lis
 
 { set +x
-$as_echo "$at_srcdir/listings.at:1833: diff prog18.lst prog.lis"
-at_fn_check_prepare_trace "listings.at:1833"
+$as_echo "$at_srcdir/listings.at:1955: diff prog18.lst prog.lis"
+at_fn_check_prepare_trace "listings.at:1955"
 ( $at_check_trace; diff prog18.lst prog.lis
 ) >>"$at_stdout" 2>>"$at_stderr" 5>&-
 at_status=$? at_failed=false
 $at_check_filter
 at_fn_diff_devnull "$at_stderr" || at_failed=:
 at_fn_diff_devnull "$at_stdout" || at_failed=:
-at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1833"
+at_fn_check_status 0 $at_status "$at_srcdir/listings.at:1955"
 $at_failed && at_fn_log_failure  \
 "prog.lis"
 $at_traceon; }
